### ISSUE TITLE
Salvataggio stringhe in Unicode

### ISSUE THREAD

**Issue by fabiosalzano** [picce/pigeoncms#7]
Ciao picce, il pol salvando delle label in russo si è accorto che i caratteri cirillici non venivano correttamente memorizzati. Abbiamo guardato nei sorgenti e ci siamo accorti che le INSERT e le UPDATE di questi campi nei vari manager (in questo caso specifico il LabelsManager), non usano il prefisso 'N'. 
Si potrebbe prefixarli sempre? Oppure su richiesta in base ad un parametro di input passato al manager? Chiedo a te quale può essere la strada migliore

**Comment by picce** [comment]
Ciao. Si direi che si può sistemare. Segno.
Il 01/giu/2015 05:01 PM, "fabiosalzano" notifications@github.com ha
scritto:

**Comment by picce** [comment]
Nelle prossime versioni i campi descrittivi in lingua (es. item.Title, .Description, Label.Value etc..) saranno di tipo nvarchar(x) anzichè varchar(x). Per fixare le versioni attuale (se necessario) basta cambiare il tipo al campo in tabella.
