### ISSUE TITLE
Cambio "tipo di dati" della proprietà DESCRIPTION in Items_Culture

### ISSUE THREAD

**Issue by manuel-mancini** [picce/pigeoncms#75]
Cambio del "tipo di dati" della proprietà DESCRIPTION nella tabella **Items_Culture** da _text_ a _ntext_ o _nvarchar_. Risolviamo cosi il problema di mancato riconoscimento di alcuni caratteri speciali durante insert/update.

**Comment by picce** [comment]
monkey
